import type { Metadata } from "next";
import { Geist, Geist_Mono, Ubuntu_Sans } from "next/font/google";
import Navbar from "@/components/elements/Navbar";
import Footer from "@/components/elements/Footer";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ubuntuSans = Ubuntu_Sans({
  variable: "--font-ubuntu-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quiz Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ubuntuSans.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Toaster
          toastOptions={{
            style: {
              borderRadius: "1rem",
              background: "var(--color-secondary)",
              color: "var(--color-tertiary)",
              border: "1px solid var(--color-tertiary)",
            },
          }}
        />
        <Footer />
      </body>
    </html>
  );
}
